src/Entity/UserInterface.php
<?php


namespace Cooolinho\Bundle\SecurityBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface as BaseUserInterface;

interface UserInterface extends BaseUserInterface
{
    public function addRole(string $role);

    public function hasRole(string $role);

    public function setEmail(string $email);

    public function getEmail();

    public function setPassword(string $password);

    public function getPlainPassword();

}

src/Resources/views/register/index.html.twig
{% extends '@CooolinhoSecurity/security/login.html.twig' %}
{% trans_default_domain 'security' %}

{% block title %}{{ 'security.registration.title'|trans }}{% endblock %}
{% block login_title %}{{ 'security.registration.title'|trans }}{% endblock %}

{% block login_body_top %}
    {% for flashError in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}
{% endblock %}

{% block form_start %}{{ form_start(form) }}{% endblock %}

{% block login_form_email %}
    {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder': 'security.user.email'|trans}}) }}
{% endblock %}

{% block login_form_password %}
    {{ form_widget(form.plainPassword.first, {'attr': {'class': 'form-control', 'placeholder': 'security.change_password.password.new'|trans}}) }}
{% endblock %}

{% block login_form_password_after %}
    <div class="input-group mb-3">
        <span class="input-group-text"><i class="fas fa-key"></i></span>
        {{ form_widget(form.plainPassword.second, {'attr': {'class': 'form-control', 'placeholder': 'security.change_password.password.repeat'|trans}}) }}
    </div>
{% endblock %}

{% block login_form_remember_me %}
    {{ form_widget(form.agreeTerms) }}
{% endblock %}

{% block login_form_end %}{{ form_end(form) }}{% endblock %}

{% block login_footer %}{% endblock %}